sudo: required
service:
  - docker

before_install:
  - docker build -t msaint/docker-react -f  Dockerfile.dev .

scripts:
  - docker run -e CI=true msaint/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-191643054305"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
